//
//  DietPlan.swift
//  HealthOptimizer
//
//  Diet and nutrition recommendation models
//

import Foundation

// MARK: - Diet Plan

/// Complete nutrition plan generated by AI
struct DietPlan: nonisolated Codable, Identifiable, Sendable {
  var id: UUID
  var name: String
  var description: String
  var dailyCalories: Int
  var macros: MacroTargets
  var mealSchedule: [MealTemplate]
  var sampleMealPlan: [DayMealPlan]  // 7 days sample
  var generalGuidelines: [String]
  var foodsToInclude: [String]
  var foodsToLimit: [String]
  var hydrationGuidelines: String
  var mealTimingGuidelines: String
  var snackingGuidelines: String
  var createdAt: Date

  init(
    id: UUID = UUID(),
    name: String = "Custom Diet Plan",
    description: String = "",
    dailyCalories: Int = 2000,
    macros: MacroTargets = MacroTargets(),
    mealSchedule: [MealTemplate] = [],
    sampleMealPlan: [DayMealPlan] = [],
    generalGuidelines: [String] = [],
    foodsToInclude: [String] = [],
    foodsToLimit: [String] = [],
    hydrationGuidelines: String = "",
    mealTimingGuidelines: String = "",
    snackingGuidelines: String = "",
    createdAt: Date = Date()
  ) {
    self.id = id
    self.name = name
    self.description = description
    self.dailyCalories = dailyCalories
    self.macros = macros
    self.mealSchedule = mealSchedule
    self.sampleMealPlan = sampleMealPlan
    self.generalGuidelines = generalGuidelines
    self.foodsToInclude = foodsToInclude
    self.foodsToLimit = foodsToLimit
    self.hydrationGuidelines = hydrationGuidelines
    self.mealTimingGuidelines = mealTimingGuidelines
    self.snackingGuidelines = snackingGuidelines
    self.createdAt = createdAt
  }
}

// MARK: - Macro Targets

/// Daily macronutrient targets
struct MacroTargets: Codable, Sendable {
  var proteinGrams: Int
  var proteinPercentage: Int
  var carbsGrams: Int
  var carbsPercentage: Int
  var fatGrams: Int
  var fatPercentage: Int
  var fiberGrams: Int
  var sugarLimitGrams: Int
  var sodiumLimitMg: Int

  init(
    proteinGrams: Int = 150,
    proteinPercentage: Int = 30,
    carbsGrams: Int = 200,
    carbsPercentage: Int = 40,
    fatGrams: Int = 67,
    fatPercentage: Int = 30,
    fiberGrams: Int = 30,
    sugarLimitGrams: Int = 50,
    sodiumLimitMg: Int = 2300
  ) {
    self.proteinGrams = proteinGrams
    self.proteinPercentage = proteinPercentage
    self.carbsGrams = carbsGrams
    self.carbsPercentage = carbsPercentage
    self.fatGrams = fatGrams
    self.fatPercentage = fatPercentage
    self.fiberGrams = fiberGrams
    self.sugarLimitGrams = sugarLimitGrams
    self.sodiumLimitMg = sodiumLimitMg
  }

  /// Display string for macro breakdown
  var macroBreakdownDisplay: String {
    "P: \(proteinGrams)g (\(proteinPercentage)%) | C: \(carbsGrams)g (\(carbsPercentage)%) | F: \(fatGrams)g (\(fatPercentage)%)"
  }
}

// MARK: - Meal Template

/// Template for a meal type (breakfast, lunch, etc.)
struct MealTemplate: Codable, Identifiable, Sendable {
  var id: UUID
  var mealType: MealType
  var targetCalories: Int
  var targetProtein: Int
  var targetCarbs: Int
  var targetFat: Int
  var suggestedTime: String
  var guidelines: String

  init(
    id: UUID = UUID(),
    mealType: MealType,
    targetCalories: Int,
    targetProtein: Int,
    targetCarbs: Int,
    targetFat: Int,
    suggestedTime: String = "",
    guidelines: String = ""
  ) {
    self.id = id
    self.mealType = mealType
    self.targetCalories = targetCalories
    self.targetProtein = targetProtein
    self.targetCarbs = targetCarbs
    self.targetFat = targetFat
    self.suggestedTime = suggestedTime
    self.guidelines = guidelines
  }
}

// MARK: - Meal Type

/// Types of meals
enum MealType: String, Codable, CaseIterable, Identifiable, Sendable {
  case breakfast = "Breakfast"
  case morningSnack = "Morning Snack"
  case lunch = "Lunch"
  case afternoonSnack = "Afternoon Snack"
  case dinner = "Dinner"
  case eveningSnack = "Evening Snack"
  case preWorkout = "Pre-Workout"
  case postWorkout = "Post-Workout"

  var id: String { rawValue }

  var icon: String {
    switch self {
    case .breakfast: return "sunrise.fill"
    case .morningSnack: return "cup.and.saucer.fill"
    case .lunch: return "sun.max.fill"
    case .afternoonSnack: return "leaf.fill"
    case .dinner: return "moon.stars.fill"
    case .eveningSnack: return "moon.fill"
    case .preWorkout: return "bolt.fill"
    case .postWorkout: return "figure.cooldown"
    }
  }

  init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    let raw = try container.decode(String.self)
    let normalized = raw.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()

    if let exact = MealType(rawValue: raw) {
      self = exact
      return
    }

    if normalized.contains("breakfast") {
      self = .breakfast
    } else if normalized.contains("lunch") {
      self = .lunch
    } else if normalized.contains("dinner") {
      self = .dinner
    } else if normalized.contains("afternoon") && normalized.contains("snack") {
      self = .afternoonSnack
    } else if (normalized.contains("morning") || normalized.contains("mid-morning"))
      && normalized.contains("snack")
    {
      self = .morningSnack
    } else if (normalized.contains("evening") || normalized.contains("pre-sleep"))
      && normalized.contains("snack")
    {
      self = .eveningSnack
    } else if normalized.contains("pre-workout") {
      self = .preWorkout
    } else if normalized.contains("post-workout") {
      self = .postWorkout
    } else {
      self = .lunch
    }
  }

  func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    try container.encode(rawValue)
  }
}

// MARK: - Day Meal Plan

/// One day's complete meal plan
struct DayMealPlan: Codable, Identifiable, Sendable {
  var id: UUID
  var dayNumber: Int  // 1-7
  var dayName: String  // Monday, Tuesday, etc.
  var meals: [Meal]
  var totalCalories: Int
  var totalProtein: Int
  var totalCarbs: Int
  var totalFat: Int
  var notes: String?

  init(
    id: UUID = UUID(),
    dayNumber: Int,
    dayName: String,
    meals: [Meal] = [],
    totalCalories: Int = 0,
    totalProtein: Int = 0,
    totalCarbs: Int = 0,
    totalFat: Int = 0,
    notes: String? = nil
  ) {
    self.id = id
    self.dayNumber = dayNumber
    self.dayName = dayName
    self.meals = meals
    self.totalCalories = totalCalories
    self.totalProtein = totalProtein
    self.totalCarbs = totalCarbs
    self.totalFat = totalFat
    self.notes = notes
  }
}

// MARK: - Meal

/// A specific meal with recipe
struct Meal: Codable, Identifiable, Sendable {
  var id: UUID
  var mealType: MealType
  var name: String
  var description: String
  var ingredients: [Ingredient]
  var instructions: [String]
  var prepTimeMinutes: Int
  var cookTimeMinutes: Int
  var servings: Int
  var calories: Int
  var protein: Int
  var carbs: Int
  var fat: Int
  var fiber: Int
  var tips: [String]
  var substitutions: [String: String]  // ingredient: substitution
  var mealPrepFriendly: Bool
  var tags: [String]  // e.g., "high-protein", "quick", "vegetarian"

  enum CodingKeys: String, CodingKey {
    case id, mealType, name, description, ingredients, instructions
    case prepTimeMinutes, cookTimeMinutes, servings
    case calories, protein, carbs, fat, fiber
    case tips, substitutions, mealPrepFriendly, tags
  }

  init(
    id: UUID = UUID(),
    mealType: MealType,
    name: String,
    description: String = "",
    ingredients: [Ingredient] = [],
    instructions: [String] = [],
    prepTimeMinutes: Int = 10,
    cookTimeMinutes: Int = 15,
    servings: Int = 1,
    calories: Int = 0,
    protein: Int = 0,
    carbs: Int = 0,
    fat: Int = 0,
    fiber: Int = 0,
    tips: [String] = [],
    substitutions: [String: String] = [:],
    mealPrepFriendly: Bool = false,
    tags: [String] = []
  ) {
    self.id = id
    self.mealType = mealType
    self.name = name
    self.description = description
    self.ingredients = ingredients
    self.instructions = instructions
    self.prepTimeMinutes = prepTimeMinutes
    self.cookTimeMinutes = cookTimeMinutes
    self.servings = servings
    self.calories = calories
    self.protein = protein
    self.carbs = carbs
    self.fat = fat
    self.fiber = fiber
    self.tips = tips
    self.substitutions = substitutions
    self.mealPrepFriendly = mealPrepFriendly
    self.tags = tags
  }

  // Helper to decode Int from Int or String
  private static func decodeInt(from container: KeyedDecodingContainer<CodingKeys>, forKey key: CodingKeys, default defaultValue: Int) -> Int {
    if let intValue = try? container.decode(Int.self, forKey: key) {
      return intValue
    } else if let stringValue = try? container.decode(String.self, forKey: key),
              let intValue = Int(stringValue) {
      return intValue
    }
    return defaultValue
  }

  // Custom decoding to handle flexible types from AI
  init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    id = try container.decodeIfPresent(UUID.self, forKey: .id) ?? UUID()
    mealType = try container.decode(MealType.self, forKey: .mealType)
    name = try container.decode(String.self, forKey: .name)
    description = try container.decodeIfPresent(String.self, forKey: .description) ?? ""
    ingredients = try container.decodeIfPresent([Ingredient].self, forKey: .ingredients) ?? []
    instructions = try container.decodeIfPresent([String].self, forKey: .instructions) ?? []

    prepTimeMinutes = Self.decodeInt(from: container, forKey: .prepTimeMinutes, default: 10)
    cookTimeMinutes = Self.decodeInt(from: container, forKey: .cookTimeMinutes, default: 15)
    servings = Self.decodeInt(from: container, forKey: .servings, default: 1)
    calories = Self.decodeInt(from: container, forKey: .calories, default: 0)
    protein = Self.decodeInt(from: container, forKey: .protein, default: 0)
    carbs = Self.decodeInt(from: container, forKey: .carbs, default: 0)
    fat = Self.decodeInt(from: container, forKey: .fat, default: 0)
    fiber = Self.decodeInt(from: container, forKey: .fiber, default: 0)

    tips = try container.decodeIfPresent([String].self, forKey: .tips) ?? []
    substitutions = try container.decodeIfPresent([String: String].self, forKey: .substitutions) ?? [:]
    mealPrepFriendly = try container.decodeIfPresent(Bool.self, forKey: .mealPrepFriendly) ?? false
    tags = try container.decodeIfPresent([String].self, forKey: .tags) ?? []
  }

  /// Total time display
  var totalTimeDisplay: String {
    let total = prepTimeMinutes + cookTimeMinutes
    if total >= 60 {
      return "\(total / 60)h \(total % 60)min"
    }
    return "\(total) min"
  }

  /// Macro display string
  var macroDisplay: String {
    "P: \(protein)g | C: \(carbs)g | F: \(fat)g"
  }
}

// MARK: - Ingredient

/// Recipe ingredient
struct Ingredient: Codable, Identifiable, Sendable {
  var id: UUID
  var name: String
  var amount: Double
  var unit: String
  var notes: String?  // e.g., "diced", "room temperature"
  var isOptional: Bool

  enum CodingKeys: String, CodingKey {
    case id, name, amount, unit, notes, isOptional
  }

  init(
    id: UUID = UUID(),
    name: String,
    amount: Double,
    unit: String,
    notes: String? = nil,
    isOptional: Bool = false
  ) {
    self.id = id
    self.name = name
    self.amount = amount
    self.unit = unit
    self.notes = notes
    self.isOptional = isOptional
  }

  // Custom decoding to handle amount as Int or Double
  init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    id = try container.decodeIfPresent(UUID.self, forKey: .id) ?? UUID()
    name = try container.decode(String.self, forKey: .name)

    // Handle amount as Int or Double
    if let amountDouble = try? container.decode(Double.self, forKey: .amount) {
      amount = amountDouble
    } else if let amountInt = try? container.decode(Int.self, forKey: .amount) {
      amount = Double(amountInt)
    } else {
      amount = 0
    }

    unit = try container.decode(String.self, forKey: .unit)
    notes = try container.decodeIfPresent(String.self, forKey: .notes)
    isOptional = try container.decodeIfPresent(Bool.self, forKey: .isOptional) ?? false
  }

  /// Display string for ingredient
  var display: String {
    var str = ""
    if amount == floor(amount) {
      str = "\(Int(amount)) \(unit) \(name)"
    } else {
      str = String(format: "%.1f %@ %@", amount, unit, name)
    }
    if let notes = notes {
      str += ", \(notes)"
    }
    if isOptional {
      str += " (optional)"
    }
    return str
  }
}

// MARK: - Sample Data

extension DietPlan {
  /// Sample diet plan for previews
  static var sample: DietPlan {
    DietPlan(
      name: "Balanced Weight Loss Plan",
      description:
        "A balanced approach to weight loss emphasizing whole foods, adequate protein, and sustainable eating habits.",
      dailyCalories: 1800,
      macros: MacroTargets(
        proteinGrams: 135,
        proteinPercentage: 30,
        carbsGrams: 180,
        carbsPercentage: 40,
        fatGrams: 60,
        fatPercentage: 30,
        fiberGrams: 30,
        sugarLimitGrams: 40
      ),
      mealSchedule: [
        MealTemplate(
          mealType: .breakfast,
          targetCalories: 400,
          targetProtein: 30,
          targetCarbs: 40,
          targetFat: 15,
          suggestedTime: "7:00 - 8:00 AM",
          guidelines: "High protein to start the day, complex carbs for energy"
        ),
        MealTemplate(
          mealType: .lunch,
          targetCalories: 500,
          targetProtein: 40,
          targetCarbs: 50,
          targetFat: 18,
          suggestedTime: "12:00 - 1:00 PM",
          guidelines: "Balanced meal with lean protein and vegetables"
        ),
        MealTemplate(
          mealType: .dinner,
          targetCalories: 550,
          targetProtein: 45,
          targetCarbs: 50,
          targetFat: 20,
          suggestedTime: "6:00 - 7:00 PM",
          guidelines: "Protein-focused with plenty of vegetables"
        ),
      ],
      sampleMealPlan: [
        DayMealPlan(
          dayNumber: 1,
          dayName: "Monday",
          meals: [
            Meal(
              mealType: .breakfast,
              name: "Greek Yogurt Protein Bowl",
              description: "Creamy Greek yogurt topped with berries, nuts, and a drizzle of honey",
              ingredients: [
                Ingredient(name: "Greek yogurt (2%)", amount: 1, unit: "cup"),
                Ingredient(name: "Mixed berries", amount: 0.5, unit: "cup"),
                Ingredient(name: "Almonds, sliced", amount: 2, unit: "tbsp"),
                Ingredient(name: "Honey", amount: 1, unit: "tsp", isOptional: true),
                Ingredient(name: "Chia seeds", amount: 1, unit: "tbsp"),
              ],
              instructions: [
                "Add Greek yogurt to a bowl",
                "Top with mixed berries",
                "Sprinkle with almonds and chia seeds",
                "Drizzle with honey if desired",
              ],
              prepTimeMinutes: 5,
              cookTimeMinutes: 0,
              servings: 1,
              calories: 380,
              protein: 28,
              carbs: 35,
              fat: 14,
              fiber: 6,
              tips: ["Prep berries ahead of time", "Use plain yogurt to control sugar"],
              mealPrepFriendly: true,
              tags: ["high-protein", "quick", "no-cook"]
            ),
            Meal(
              mealType: .lunch,
              name: "Grilled Chicken Salad",
              description:
                "Fresh mixed greens with grilled chicken breast, vegetables, and olive oil dressing",
              ingredients: [
                Ingredient(name: "Chicken breast, grilled", amount: 6, unit: "oz"),
                Ingredient(name: "Mixed greens", amount: 3, unit: "cups"),
                Ingredient(name: "Cherry tomatoes", amount: 0.5, unit: "cup"),
                Ingredient(name: "Cucumber, diced", amount: 0.5, unit: "cup"),
                Ingredient(name: "Olive oil", amount: 1, unit: "tbsp"),
                Ingredient(name: "Balsamic vinegar", amount: 1, unit: "tbsp"),
              ],
              instructions: [
                "Grill or pan-sear chicken breast until cooked through",
                "Let chicken rest 5 minutes, then slice",
                "Arrange greens in a large bowl",
                "Top with chicken, tomatoes, and cucumber",
                "Drizzle with olive oil and balsamic",
              ],
              prepTimeMinutes: 10,
              cookTimeMinutes: 15,
              servings: 1,
              calories: 420,
              protein: 45,
              carbs: 12,
              fat: 22,
              fiber: 4,
              substitutions: ["Chicken": "Tofu or salmon"],
              mealPrepFriendly: true,
              tags: ["high-protein", "low-carb", "meal-prep"]
            ),
          ],
          totalCalories: 1800,
          totalProtein: 135,
          totalCarbs: 180,
          totalFat: 60
        )
      ],
      generalGuidelines: [
        "Eat protein with every meal to maintain muscle and control hunger",
        "Fill half your plate with vegetables",
        "Choose whole grains over refined carbohydrates",
        "Limit processed foods and added sugars",
        "Plan and prep meals to stay consistent",
      ],
      foodsToInclude: [
        "Lean proteins (chicken, fish, tofu, legumes)",
        "Colorful vegetables",
        "Whole grains (quinoa, brown rice, oats)",
        "Healthy fats (olive oil, avocado, nuts)",
        "Fresh fruits in moderation",
      ],
      foodsToLimit: [
        "Processed snacks and desserts",
        "Sugary beverages",
        "Fried foods",
        "Refined carbohydrates",
        "Excessive alcohol",
      ],
      hydrationGuidelines: "Aim for 8-10 glasses (64-80 oz) of water daily. More on workout days.",
      mealTimingGuidelines:
        "Eat within 1 hour of waking, space meals 3-4 hours apart, finish eating 2-3 hours before bed.",
      snackingGuidelines:
        "If hungry between meals, choose protein-rich snacks like Greek yogurt, nuts, or hard-boiled eggs."
    )
  }
}
