//
//  SupplementPlan.swift
//  HealthOptimizer
//
//  Supplement recommendation models
//

import Foundation

// MARK: - Supplement Plan

/// Complete supplementation plan generated by AI
struct SupplementPlan: Codable, Identifiable {
    var id: UUID
    var supplements: [SupplementRecommendation]
    var generalGuidelines: String
    var warnings: [String]
    var interactionNotes: [String]
    var createdAt: Date
    
    init(
        id: UUID = UUID(),
        supplements: [SupplementRecommendation] = [],
        generalGuidelines: String = "",
        warnings: [String] = [],
        interactionNotes: [String] = [],
        createdAt: Date = Date()
    ) {
        self.id = id
        self.supplements = supplements
        self.generalGuidelines = generalGuidelines
        self.warnings = warnings
        self.interactionNotes = interactionNotes
        self.createdAt = createdAt
    }
    
    /// Group supplements by timing for display
    var supplementsByTiming: [SupplementTiming: [SupplementRecommendation]] {
        Dictionary(grouping: supplements) { $0.timing }
    }
    
    /// Priority supplements (essentials)
    var prioritySupplements: [SupplementRecommendation] {
        supplements.filter { $0.priority == .essential }
    }
}

// MARK: - Supplement Recommendation

/// Individual supplement recommendation
struct SupplementRecommendation: Codable, Identifiable {
    var id: UUID
    var name: String
    var alternateNames: [String]  // Common brand names or forms
    var dosage: String
    var unit: String
    var timing: SupplementTiming
    var frequency: SupplementFrequency
    var withFood: Bool
    var priority: SupplementPriority
    var reasoning: String
    var scientificBacking: String
    var benefits: [String]
    var potentialSideEffects: [String]
    var interactions: [String]
    var contraindications: [String]
    var qualityNotes: String?  // What to look for when purchasing
    var estimatedMonthlyCost: String?  // Price range
    var duration: String?  // How long to take (if not indefinite)
    
    init(
        id: UUID = UUID(),
        name: String,
        alternateNames: [String] = [],
        dosage: String,
        unit: String = "mg",
        timing: SupplementTiming = .morning,
        frequency: SupplementFrequency = .daily,
        withFood: Bool = true,
        priority: SupplementPriority = .recommended,
        reasoning: String = "",
        scientificBacking: String = "",
        benefits: [String] = [],
        potentialSideEffects: [String] = [],
        interactions: [String] = [],
        contraindications: [String] = [],
        qualityNotes: String? = nil,
        estimatedMonthlyCost: String? = nil,
        duration: String? = nil
    ) {
        self.id = id
        self.name = name
        self.alternateNames = alternateNames
        self.dosage = dosage
        self.unit = unit
        self.timing = timing
        self.frequency = frequency
        self.withFood = withFood
        self.priority = priority
        self.reasoning = reasoning
        self.scientificBacking = scientificBacking
        self.benefits = benefits
        self.potentialSideEffects = potentialSideEffects
        self.interactions = interactions
        self.contraindications = contraindications
        self.qualityNotes = qualityNotes
        self.estimatedMonthlyCost = estimatedMonthlyCost
        self.duration = duration
    }
    
    /// Full dosage display string
    var dosageDisplay: String {
        "\(dosage) \(unit)"
    }
    
    /// Complete timing description
    var timingDescription: String {
        var desc = timing.rawValue
        if withFood {
            desc += " with food"
        } else {
            desc += " on empty stomach"
        }
        return desc
    }
}

// MARK: - Supplement Timing

/// When to take supplements
enum SupplementTiming: String, Codable, CaseIterable, Identifiable {
    case morning = "Morning"
    case midday = "Midday"
    case afternoon = "Afternoon"
    case evening = "Evening"
    case beforeBed = "Before Bed"
    case preWorkout = "Pre-Workout"
    case postWorkout = "Post-Workout"
    case withMeals = "With Meals"
    case betweenMeals = "Between Meals"
    case asNeeded = "As Needed"
    
    var id: String { rawValue }
    
    var icon: String {
        switch self {
        case .morning: return "sunrise.fill"
        case .midday: return "sun.max.fill"
        case .afternoon: return "sun.haze.fill"
        case .evening: return "sunset.fill"
        case .beforeBed: return "moon.fill"
        case .preWorkout: return "figure.run"
        case .postWorkout: return "figure.cooldown"
        case .withMeals: return "fork.knife"
        case .betweenMeals: return "clock.fill"
        case .asNeeded: return "questionmark.circle.fill"
        }
    }
    
    /// Suggested time of day
    var suggestedTime: String {
        switch self {
        case .morning: return "6:00 - 8:00 AM"
        case .midday: return "12:00 - 1:00 PM"
        case .afternoon: return "3:00 - 4:00 PM"
        case .evening: return "6:00 - 7:00 PM"
        case .beforeBed: return "9:00 - 10:00 PM"
        case .preWorkout: return "30-60 min before exercise"
        case .postWorkout: return "Within 30 min after exercise"
        case .withMeals: return "During meals"
        case .betweenMeals: return "2-3 hours after eating"
        case .asNeeded: return "When symptoms occur"
        }
    }
}

// MARK: - Supplement Frequency

/// How often to take a supplement
enum SupplementFrequency: String, Codable, CaseIterable, Identifiable {
    case daily = "Daily"
    case twiceDaily = "Twice Daily"
    case threeTimesDaily = "Three Times Daily"
    case everyOtherDay = "Every Other Day"
    case weekly = "Weekly"
    case asNeeded = "As Needed"
    case cyclic = "Cyclic (see notes)"
    
    var id: String { rawValue }
}

// MARK: - Supplement Priority

/// Priority level for supplement recommendations
enum SupplementPriority: String, Codable, CaseIterable, Identifiable {
    case essential = "Essential"
    case recommended = "Highly Recommended"
    case beneficial = "Beneficial"
    case optional = "Optional/Consider"
    
    var id: String { rawValue }
    
    var color: String {
        switch self {
        case .essential: return "red"
        case .recommended: return "orange"
        case .beneficial: return "blue"
        case .optional: return "gray"
        }
    }
    
    var sortOrder: Int {
        switch self {
        case .essential: return 0
        case .recommended: return 1
        case .beneficial: return 2
        case .optional: return 3
        }
    }
}

// MARK: - Sample Data

extension SupplementPlan {
    /// Sample supplement plan for previews
    static var sample: SupplementPlan {
        SupplementPlan(
            supplements: [
                SupplementRecommendation(
                    name: "Vitamin D3",
                    alternateNames: ["Cholecalciferol"],
                    dosage: "5000",
                    unit: "IU",
                    timing: .morning,
                    withFood: true,
                    priority: .essential,
                    reasoning: "Most adults are deficient, especially with indoor lifestyle. Critical for immune function, bone health, and mood.",
                    scientificBacking: "Multiple meta-analyses show benefits for immunity, bone health, and mood. Blood levels of 40-60 ng/mL are optimal.",
                    benefits: ["Immune support", "Bone health", "Mood regulation", "Muscle function"],
                    potentialSideEffects: ["Rare at recommended doses", "Hypercalcemia at very high doses"],
                    qualityNotes: "Look for D3 (not D2), ideally with K2 for synergy",
                    estimatedMonthlyCost: "$10-20"
                ),
                SupplementRecommendation(
                    name: "Magnesium Glycinate",
                    alternateNames: ["Magnesium Bisglycinate"],
                    dosage: "400",
                    unit: "mg",
                    timing: .beforeBed,
                    withFood: false,
                    priority: .essential,
                    reasoning: "Supports sleep quality, stress management, and muscle recovery. Most diets are deficient.",
                    scientificBacking: "Well-absorbed form with research supporting sleep and anxiety benefits.",
                    benefits: ["Better sleep", "Reduced stress", "Muscle relaxation", "Heart health"],
                    potentialSideEffects: ["Loose stools at high doses"],
                    qualityNotes: "Glycinate form is best for sleep; avoid oxide form (poor absorption)",
                    estimatedMonthlyCost: "$15-25"
                ),
                SupplementRecommendation(
                    name: "Omega-3 Fish Oil",
                    alternateNames: ["EPA/DHA", "Fish Oil"],
                    dosage: "2000",
                    unit: "mg EPA+DHA",
                    timing: .withMeals,
                    withFood: true,
                    priority: .recommended,
                    reasoning: "Anti-inflammatory support for heart, brain, and joint health.",
                    scientificBacking: "Extensive research on cardiovascular benefits and inflammation reduction.",
                    benefits: ["Heart health", "Brain function", "Joint support", "Inflammation reduction"],
                    potentialSideEffects: ["Fish burps (use enteric-coated)", "Blood thinning at high doses"],
                    interactions: ["Blood thinners - consult doctor"],
                    qualityNotes: "Look for triglyceride form, third-party tested for purity (IFOS certified)",
                    estimatedMonthlyCost: "$20-40"
                )
            ],
            generalGuidelines: "Start with essential supplements first, then add others gradually. Take with meals unless otherwise noted. Stay consistent for best results.",
            warnings: ["Always consult your healthcare provider before starting new supplements, especially with existing conditions or medications."],
            interactionNotes: ["No significant interactions identified with your current medications."]
        )
    }
}
