//
//  WorkoutPlan.swift
//  HealthOptimizer
//
//  Workout and exercise recommendation models
//

import Foundation

// MARK: - Workout Plan

/// Complete workout program generated by AI
struct WorkoutPlan: Codable, Identifiable, Sendable {
    var id: UUID
    var name: String
    var description: String
    var durationWeeks: Int
    var daysPerWeek: Int
    var workoutDays: [WorkoutDay]
    var restDayGuidelines: String
    var warmupGuidelines: String
    var cooldownGuidelines: String
    var progressionNotes: String
    var equipmentNeeded: [String]
    var difficultyLevel: FitnessLevel
    var estimatedCaloriesBurnedPerSession: String
    var createdAt: Date
    
    init(
        id: UUID = UUID(),
        name: String = "Custom Workout Plan",
        description: String = "",
        durationWeeks: Int = 8,
        daysPerWeek: Int = 4,
        workoutDays: [WorkoutDay] = [],
        restDayGuidelines: String = "",
        warmupGuidelines: String = "",
        cooldownGuidelines: String = "",
        progressionNotes: String = "",
        equipmentNeeded: [String] = [],
        difficultyLevel: FitnessLevel = .intermediate,
        estimatedCaloriesBurnedPerSession: String = "",
        createdAt: Date = Date()
    ) {
        self.id = id
        self.name = name
        self.description = description
        self.durationWeeks = durationWeeks
        self.daysPerWeek = daysPerWeek
        self.workoutDays = workoutDays
        self.restDayGuidelines = restDayGuidelines
        self.warmupGuidelines = warmupGuidelines
        self.cooldownGuidelines = cooldownGuidelines
        self.progressionNotes = progressionNotes
        self.equipmentNeeded = equipmentNeeded
        self.difficultyLevel = difficultyLevel
        self.estimatedCaloriesBurnedPerSession = estimatedCaloriesBurnedPerSession
        self.createdAt = createdAt
    }
}

// MARK: - Workout Day

/// A single day's workout routine
struct WorkoutDay: Codable, Identifiable, Sendable {
    var id: UUID
    var dayNumber: Int  // 1-7 for weekly schedule
    var name: String  // e.g., "Upper Body Push", "Leg Day"
    var focus: [MuscleGroup]
    var workoutType: WorkoutType
    var exercises: [Exercise]
    var estimatedDuration: Int  // minutes
    var notes: String?
    
    init(
        id: UUID = UUID(),
        dayNumber: Int,
        name: String,
        focus: [MuscleGroup] = [],
        workoutType: WorkoutType = .strength,
        exercises: [Exercise] = [],
        estimatedDuration: Int = 45,
        notes: String? = nil
    ) {
        self.id = id
        self.dayNumber = dayNumber
        self.name = name
        self.focus = focus
        self.workoutType = workoutType
        self.exercises = exercises
        self.estimatedDuration = estimatedDuration
        self.notes = notes
    }
}

// MARK: - Exercise

/// Individual exercise with details
struct Exercise: Codable, Identifiable, Sendable {
    var id: UUID
    var name: String
    var muscleGroups: [MuscleGroup]
    var sets: Int
    var reps: String  // String to allow "8-12" or "AMRAP"
    var restSeconds: Int
    var weight: String?  // e.g., "Bodyweight", "Moderate", specific weight
    var tempo: String?  // e.g., "3-1-2" for eccentric-pause-concentric
    var rpe: Int?  // Rate of Perceived Exertion 1-10
    var instructions: String
    var tips: [String]
    var commonMistakes: [String]
    var alternatives: [String]  // Exercise substitutions
    var videoURL: String?  // For future implementation
    var isSuperset: Bool
    var supersetWith: String?  // Name of paired exercise
    
    init(
        id: UUID = UUID(),
        name: String,
        muscleGroups: [MuscleGroup] = [],
        sets: Int = 3,
        reps: String = "10",
        restSeconds: Int = 60,
        weight: String? = nil,
        tempo: String? = nil,
        rpe: Int? = nil,
        instructions: String = "",
        tips: [String] = [],
        commonMistakes: [String] = [],
        alternatives: [String] = [],
        videoURL: String? = nil,
        isSuperset: Bool = false,
        supersetWith: String? = nil
    ) {
        self.id = id
        self.name = name
        self.muscleGroups = muscleGroups
        self.sets = sets
        self.reps = reps
        self.restSeconds = restSeconds
        self.weight = weight
        self.tempo = tempo
        self.rpe = rpe
        self.instructions = instructions
        self.tips = tips
        self.commonMistakes = commonMistakes
        self.alternatives = alternatives
        self.videoURL = videoURL
        self.isSuperset = isSuperset
        self.supersetWith = supersetWith
    }
    
    /// Display string for sets and reps
    var setsRepsDisplay: String {
        "\(sets) × \(reps)"
    }
    
    /// Rest time display
    var restDisplay: String {
        if restSeconds >= 60 {
            let minutes = restSeconds / 60
            let seconds = restSeconds % 60
            if seconds == 0 {
                return "\(minutes) min rest"
            }
            return "\(minutes):\(String(format: "%02d", seconds)) rest"
        }
        return "\(restSeconds)s rest"
    }
}

// MARK: - Muscle Group

/// Target muscle groups
enum MuscleGroup: String, Codable, CaseIterable, Identifiable, Sendable {
    // Upper Body Push
    case chest = "Chest"
    case shoulders = "Shoulders"
    case triceps = "Triceps"
    
    // Upper Body Pull
    case back = "Back"
    case biceps = "Biceps"
    case forearms = "Forearms"
    
    // Core
    case abs = "Abs"
    case obliques = "Obliques"
    case lowerBack = "Lower Back"
    
    // Lower Body
    case quads = "Quadriceps"
    case hamstrings = "Hamstrings"
    case glutes = "Glutes"
    case calves = "Calves"
    case hipFlexors = "Hip Flexors"
    
    // Full Body
    case fullBody = "Full Body"
    
    var id: String { rawValue }
    
    var icon: String {
        switch self {
        case .chest: return "figure.arms.open"
        case .shoulders: return "figure.arms.open"
        case .triceps: return "figure.arms.open"
        case .back: return "figure.stand"
        case .biceps: return "figure.arms.open"
        case .forearms: return "hand.raised.fill"
        case .abs, .obliques: return "figure.core.training"
        case .lowerBack: return "figure.stand"
        case .quads, .hamstrings, .glutes, .calves, .hipFlexors: return "figure.walk"
        case .fullBody: return "figure.mixed.cardio"
        }
    }
}

// MARK: - Workout Type

/// Type of workout
enum WorkoutType: String, Codable, CaseIterable, Identifiable, Sendable {
    case strength = "Strength Training"
    case hypertrophy = "Hypertrophy (Muscle Building)"
    case endurance = "Muscular Endurance"
    case cardio = "Cardio"
    case hiit = "HIIT"
    case flexibility = "Flexibility/Mobility"
    case recovery = "Active Recovery"
    case power = "Power/Explosive"
    case circuit = "Circuit Training"
    
    var id: String { rawValue }
    
    var description: String {
        switch self {
        case .strength:
            return "Heavy weights, low reps (1-6), long rest"
        case .hypertrophy:
            return "Moderate weights, medium reps (8-12), moderate rest"
        case .endurance:
            return "Light weights, high reps (15+), short rest"
        case .cardio:
            return "Sustained aerobic activity"
        case .hiit:
            return "High intensity intervals with rest periods"
        case .flexibility:
            return "Stretching and mobility work"
        case .recovery:
            return "Light activity for recovery"
        case .power:
            return "Explosive movements, moderate weights"
        case .circuit:
            return "Multiple exercises with minimal rest"
        }
    }
}

// MARK: - Sample Data

extension WorkoutPlan {
    /// Sample workout plan for previews
    static var sample: WorkoutPlan {
        WorkoutPlan(
            name: "Beginner Full Body Program",
            description: "A balanced 3-day full body program designed for beginners focusing on building strength foundation and proper movement patterns.",
            durationWeeks: 8,
            daysPerWeek: 3,
            workoutDays: [
                WorkoutDay(
                    dayNumber: 1,
                    name: "Full Body A",
                    focus: [.chest, .back, .quads],
                    workoutType: .hypertrophy,
                    exercises: [
                        Exercise(
                            name: "Barbell Squat",
                            muscleGroups: [.quads, .glutes, .hamstrings],
                            sets: 3,
                            reps: "8-10",
                            restSeconds: 90,
                            rpe: 7,
                            instructions: "Stand with feet shoulder-width apart, bar on upper back. Descend by breaking at hips and knees, keeping chest up. Drive through heels to stand.",
                            tips: ["Keep core braced", "Knees track over toes", "Full depth if mobility allows"],
                            commonMistakes: ["Knees caving in", "Rounding lower back", "Rising on toes"],
                            alternatives: ["Goblet Squat", "Leg Press", "Bulgarian Split Squat"]
                        ),
                        Exercise(
                            name: "Bench Press",
                            muscleGroups: [.chest, .shoulders, .triceps],
                            sets: 3,
                            reps: "8-10",
                            restSeconds: 90,
                            rpe: 7,
                            instructions: "Lie on bench, grip bar slightly wider than shoulders. Lower to chest with control, press up to lockout.",
                            tips: ["Retract shoulder blades", "Feet flat on floor", "Bar path slight diagonal"],
                            commonMistakes: ["Flaring elbows too wide", "Bouncing off chest", "Lifting hips"],
                            alternatives: ["Dumbbell Press", "Push-ups", "Machine Chest Press"]
                        ),
                        Exercise(
                            name: "Bent Over Row",
                            muscleGroups: [.back, .biceps],
                            sets: 3,
                            reps: "8-10",
                            restSeconds: 90,
                            rpe: 7,
                            instructions: "Hinge at hips, back flat, pull bar to lower chest/upper abs. Lower with control.",
                            tips: ["Lead with elbows", "Squeeze shoulder blades", "Keep core tight"],
                            commonMistakes: ["Rounding back", "Using momentum", "Not full range of motion"],
                            alternatives: ["Dumbbell Row", "Cable Row", "Machine Row"]
                        )
                    ],
                    estimatedDuration: 45
                ),
                WorkoutDay(
                    dayNumber: 3,
                    name: "Full Body B",
                    focus: [.shoulders, .hamstrings, .back],
                    workoutType: .hypertrophy,
                    exercises: [
                        Exercise(
                            name: "Romanian Deadlift",
                            muscleGroups: [.hamstrings, .glutes, .lowerBack],
                            sets: 3,
                            reps: "10-12",
                            restSeconds: 90,
                            instructions: "Hold bar at hips, push hips back while keeping legs nearly straight. Feel stretch in hamstrings, return to start."
                        ),
                        Exercise(
                            name: "Overhead Press",
                            muscleGroups: [.shoulders, .triceps],
                            sets: 3,
                            reps: "8-10",
                            restSeconds: 90,
                            instructions: "Press bar from shoulders to overhead, fully extending arms. Lower with control."
                        ),
                        Exercise(
                            name: "Lat Pulldown",
                            muscleGroups: [.back, .biceps],
                            sets: 3,
                            reps: "10-12",
                            restSeconds: 60,
                            instructions: "Pull bar to upper chest, squeezing shoulder blades together. Return with control."
                        )
                    ],
                    estimatedDuration: 45
                )
            ],
            restDayGuidelines: "Take complete rest or do light activity like walking. Focus on sleep and nutrition for recovery.",
            warmupGuidelines: "5-10 minutes of light cardio followed by dynamic stretches. Do 1-2 warm-up sets of each exercise with light weight.",
            cooldownGuidelines: "5 minutes of light cardio, followed by static stretching of worked muscle groups.",
            progressionNotes: "Add 5lbs to lifts when you can complete all sets at the top of the rep range with good form. Deload every 4th week.",
            equipmentNeeded: ["Barbell", "Dumbbells", "Bench", "Cable Machine"],
            difficultyLevel: .beginner,
            estimatedCaloriesBurnedPerSession: "200-350 calories"
        )
    }
}
